### ISSUE TITLE
Susbetting using "-" 

### ISSUE THREAD

**Issue by philouail** [rformassspectrometry/MsExperiment#37] opened 2023-10-09 13:31 UTC
When trying to subset using "-"  the subsetting does not work properly: 

example: 

```r
data

``` 

```
> data
Object of class MsExperiment 
 Spectra: MS1 (225898) 
 Experiment data: 632 sample(s)
 Sample data links:
  - spectra: 631 sample(s) to 225898 element(s).
``` 

I try to remove a specific sample: 

```r
data <- data[-147]
data
``` 

return: 

```
> data
Object of class MsExperiment 
 Spectra: MS () 
 Experiment data: 631 sample(s)
 Sample data links:
  - spectra: 0 sample(s) to 0 element(s).
``` 

So all of the spectra got somehow removed.

**Comment by lgatto** [comment] 2023-10-09 14:22
Thanks - this indeed looks like a bug that can be reproduced with the `mse` from `?MsExperiment`.

**Comment by jorainer** [comment] 2023-10-27 10:08
Fixed now.

**Closed as completed by jorainer** 2023-10-27 10:08 UTC
Labels: bug
